--------------------------------------------------------
--  DDL for Table METRO
--------------------------------------------------------

  CREATE TABLE "HR"."METRO" 
   (	"역이름" VARCHAR2(200 BYTE), 
	"Y" NUMBER(38,8), 
	"X" NUMBER(38,7), 
	"호선" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
